server:
  port: 8081
  servlet:
    context-path: /springboot02

spring:
  datasource:
    url: jdbc:mysql://82.156.183.203:12345/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jmx:
    enabled: true
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.ce.pojo
